//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.23 at 11:24:13 AM PST 
//


package org.pvv.larschri.gameday.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.pvv.larschri.gameday.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.pvv.larschri.gameday.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InningAll.Inning.Top }
     * 
     */
    public InningAll.Inning.HalfInning createGameInningTop() {
        return new InningAll.Inning.HalfInning();
    }

    /**
     * Create an instance of {@link InningAll.Inning.HalfInning.Atbat }
     * 
     */
    public InningAll.Inning.HalfInning.Atbat createGameInningBottomAtbat() {
        return new InningAll.Inning.HalfInning.Atbat();
    }

    /**
     * Create an instance of {@link InningAll.Inning.Top.Atbat.Pitch }
     * 
     */
    public InningAll.Inning.HalfInning.Atbat.Pitch createGameInningTopAtbatPitch() {
        return new InningAll.Inning.HalfInning.Atbat.Pitch();
    }

    /**
     * Create an instance of {@link InningAll.Inning.HalfInning }
     * 
     */
    public InningAll.Inning.HalfInning createGameInningBottom() {
        return new InningAll.Inning.HalfInning();
    }

    /**
     * Create an instance of {@link InningAll.Inning }
     * 
     */
    public InningAll.Inning createGameInning() {
        return new InningAll.Inning();
    }

    /**
     * Create an instance of {@link InningAll.Inning.HalfInning.Atbat.Pitch }
     * 
     */
    public InningAll.Inning.HalfInning.Atbat.Pitch createGameInningBottomAtbatPitch() {
        return new InningAll.Inning.HalfInning.Atbat.Pitch();
    }

    /**
     * Create an instance of {@link InningAll }
     * 
     */
    public InningAll createGame() {
        return new InningAll();
    }

    /**
     * Create an instance of {@link InningAll.Inning.Top.Atbat }
     * 
     */
    public InningAll.Inning.HalfInning.Atbat createGameInningTopAtbat() {
        return new InningAll.Inning.HalfInning.Atbat();
    }

}
